name: Update Lotte Game JSON

on:
  schedule:
    - cron: '0 4 * * *'  # 매일 13:00 KST (UTC 4시)
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install selenium beautifulsoup4

    - name: Run script
      run: python get_lotte_schedule.py

    - name: Commit and push
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add lotte_today.json
        git commit -m '자동 업데이트: 경기 일정' || echo "No changes"
        git push
